services:
  Espin\FormScrDefaultBundle\EventListener\FormInsertTags:
    public: true
    arguments:
      - '@request_stack'
    tags:
      - name: contao.hook
        hook: replaceInsertTags
        method: replaceInsertTags
